[package]
name = "site-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
reqwest = { version = "0.12.24", features = ["blocking", "rustls-tls"] }
winrt-notification = "0.5.1"

